### Задание 1

In [58]:
import numpy as np
a = np.array([[1,2,3,3,1],[6,8,11,10,7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [59]:
mean_a = np.mean(a1, axis=1)
mean_a

array([2. , 8.4])

### Задание 2

In [60]:
a_centered = a - mean_a.reshape(2,1)
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

### Задание 3

In [62]:
a_centered_sp = a_centered[0] @ a_centered[1]
N = a.shape[1]
a_centered_sp / (N - 1)

2.0